### ISSUE TITLE
Add audio player support for playing audio responses

### ISSUE THREAD

**Issue by ashitaprasad** [foss42/api-dash#18]
**Use case**

User should be able to directly play the audio in the response pane when the response is of content type audio/ogg, audio/aac, etc. Full list of mimetypes available [here](https://www.iana.org/assignments/media-types/media-types.xhtml#audio). Currently, the app allows users to download the audio response.

**Comment by Harsh1350** [comment]
I want to solve this issue Please assign me this @ashitaprasad 
I am GSSoC'23 contributor

**Comment by ayush-raj26** [comment]
I would like to solve this issue please assign me this project @ashitaprasad.
I am a GsSoC'23 Contributor.

**Comment by ashitaprasad** [comment]
Hi @yash-jain-1 @Harsh1350 @ayush-raj26,
Firstly, Join our [discord server](https://bit.ly/heyfoss) so that you can message on the **#foss** channel whenever you encounter any issue. That is also our official channel where we have all discussions related to API Dash.
You must also follow the [Contribution Guidelines](https://github.com/foss42/api-dash/blob/main/CONTRIBUTING.md).
We currently do not assign an issue to a single person, as it might not be the best approach. 
Also, before sending a PR, just let me know when your code is ready for review.

**Comment by animator** [comment]
@Dushant-Bansal go ahead and send a PR.
