### ISSUE TITLE
 Unable to Rename Requests in CollectionPane

### ISSUE THREAD

**Issue by caiojesu** [foss42/api-dash#2]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently, in the application, I am unable to rename requests in the `CollectionPane`, which makes it difficult to read and identify the request names. This feature is crucial to improve the usability and organization of the requests.

**Describe the solution/feature you'd like us to add**
I would like to request the addition of a feature that allows users to rename requests in the `CollectionPane`. This will enhance the user experience and enable better organization and identification of requests.

**Any other feedback you would like to provide regarding the site**
Overall, the API-Client is a great application. Thank you for your hard work on this project.

**Comment by ashitaprasad** [comment]
Hi @caiojesu,
Thanks for using API Dash and providing this valuable feedback. 
We have added this feature in the roadmap and will work on adding it to the tool.

**Comment by animator** [comment]
This feature has been added in the main branch and will be closed when it is generally available in the next release.

**Comment by animator** [comment]
Hi @caiojesu , 
API Dash v0.2.0 is now live and includes this feature. 🎉
Would definitely love to hear your feedback.
