### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [foss42/api-dash#29]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
check repo status

**Describe the solution/feature you'd like us to add**
I want to add readme badges 

![badges](https://github.com/foss42/api-dash/assets/104543751/33afe897-4382-4fa4-9a01-f1814b2bbbc1)

**Comment by animator** [comment]
Unfortunately, all the information displayed in these badges (stars, PRs, licence, etc.) are already displayed in the github repo. So there is no need of this redundancy. We have already added a badge for our Discord server which is an additional important info.

We appreciate your spirit to contribute to this project and recommend you to **open a new issue** and work on a user guide/documentation which can help users provided step by step guide (with images) on how they can use API Dash. It would be a very meaningful contribution and definitely help this project.
