### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by Wishmater** [foss42/api-dash#3]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Dark Mode UI. This is a must for dev/data-driven apps that users will look at for long periods of time.

**Describe the solution/feature you'd like us to add**
The app should automatically adapt to the default mode of the OS, and also maybe have an option for manually changing it.

**Any other feedback you would like to provide regarding the site**
The UI in the app looks great, dark mode would allow users to appretiate it even more.

**Comment by ashitaprasad** [comment]
Hi @Wishmater,
Thanks for using API Dash and providing this valuable feedback on adding Dark Mode. 
We are currently working on this feature and you will find it in the upcoming release very soon.
Will also update this issue once it is shipped.

**Comment by animator** [comment]
Hi @Wishmater, 
API Dash v0.2.0 is now live with full Dark Mode Support. 🎉
Would definitely love to hear your feedback.
