### ISSUE TITLE
Add back to top button 

### ISSUE THREAD

**Issue by S-ishita** [foss42/api-dash#30]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
I need to manually scroll up to top in readme 

**Describe the solution/feature you'd like us to add**
I want to add scroll to top button in readme 

**Any other feedback you would like to provide regarding the site**
_Your response here_

**Comment by Drishtianand19** [comment]
Would like to work on this issue can u please assign me this issue? @animator

**Comment by animator** [comment]
We are currently using a `Markdown` widget to render Home Page. @S-ishita @Drishtianand19 you can explore how to add a back to top button and send across a PR for review.

**Comment by S-ishita** [comment]
Hey @animator this issue isn't regarding homepage it is regarding the readme file

**Comment by animator** [comment]
@S-ishita Can you share a screenshot where you want to add the button or you can also directly send a PR. Will review and comment.

**Comment by S-ishita** [comment]
Kindly review pr and please add me as assignee as well

**Comment by animator** [comment]
Hi @S-ishita,
I reviewed the PR. 
GitHub already provides a sticky navigation drawer (with Table of Contents), which can be used to navigate anywhere in the readme. So this back to top button is redundant and adds additional html elements to the readme that are not required.


<img width="1059" alt="Screenshot 2023-05-22 at 6 54 49 PM" src="https://github.com/foss42/api-dash/assets/615622/5ac3a0cc-4613-4b09-98af-a9d14b6df541">
