### ISSUE TITLE
Need to update Flutter Project (api-dash) Dependencies

### ISSUE THREAD

**Issue by andoriyaprashant** [foss42/api-dash#31]
**Describe the bug/problem**

This Flutter project (api-dash) is outdated, it is crucial to keep the project dependencies and versions up to date to leverage the latest features, bug fixes, and improvements offered by the Flutter ecosystem and its associated packages.

To resolve this issue, the dependencies listed in the project's "pubspec.yaml" file need to be updated to their latest versions.

Dependencies for upgrade --

![Screenshot 2023-05-21 235627](https://github.com/foss42/api-dash/assets/121665385/9415cac5-8d23-4824-bb82-5fc6cb15e6ac)

**Steps to Reproduce the bug/problem**

1. Go to pubspec.yaml file and build.gradle file for check the version
2. Click on terminal and type "flutter pub get" to know the updates.
3. Scroll down to see the updates

**Expected behavior**

   Version up to date

**Comment by andoriyaprashant** [comment]
Hey @animator Can you Please review this issue and My pull request #32 
Thank you

**Comment by Drishtianand19** [comment]
I am interested in contributing to this project can u please assign me this issue? @animator
