### ISSUE TITLE
Error: This requires the experimental 'records' language feature to be enabled. Try passing the '--enable-experiment=records' command line option.       return (response, stopwatch.elapsed, null);

### ISSUE THREAD

**Issue by mazab99** [foss42/api-dash#4]
Error: This requires the experimental 'records' language feature to be enabled.
Try passing the '--enable-experiment=records' command line option.
      return (response, stopwatch.elapsed, null);

**Comment by animator** [comment]
The build process currently requires experimental features to be enabled as suggested in the error message.
To use API Dash, it is recommended you use the installers for stable release provided here - https://github.com/foss42/api-dash#download
