### ISSUE TITLE
Add a dropdown for language(library) selection in code pane.

### ISSUE THREAD

**Issue by mmjsmohit** [foss42/api-dash#40]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Switching between languages(libraries) to dynamically generate code using the code generation feature.

**Describe the solution/feature you'd like us to add**
A dropdown in code pane to switch between languages(libraries). It should be set to Dart by default and should present with a list of all the supported languages(libraries). It should also support search functionality. 

**Any other feedback you would like to provide regarding the site**
No

**Comment by mmjsmohit** [comment]
I would like to work on this issue! Please let me know if something like this will do:

![image](https://github.com/foss42/api-dash/assets/65406090/42b61879-41ae-42a5-b13d-c11c569db578)

**Comment by animator** [comment]
Looks good ... The labels are just missing corresponding libraries in brackets .. like it should be `Dart (http)` and `Kotlin (OkHttp)`.
