### ISSUE TITLE
Readme Error : Demo video not playing

### ISSUE THREAD

**Issue by Pratik-11** [foss42/api-dash#42]
The Video which is supposed to play in readme is'nt playing

![New Tab - Brave 5_27_2023 10_17_37 PM](https://github.com/foss42/api-dash/assets/72139212/93ab9081-ef97-406b-aead-337f7855fe7f)

Its Supposed to play right there in the readme section

**Comment by ashitaprasad** [comment]
Hi @Pratik-11,
The demo video is playing fine at our end. Can you kindly check your internet connection or change browser. 

Screen Recording at our end below 👇

https://github.com/foss42/api-dash/assets/1382619/86c177a8-bc40-4ab6-9dc9-634aa868c715

**Comment by Pratik-11** [comment]
**Update :**
Yes @ashitaprasad You're right ,I checked its working fine on chrome and Microsoft Edge but its not working on Brave(I primarily use brave so i saw this issue ). Kindly try on brave once so we can confirm its a browser issue or an issue on my side

**Comment by ashitaprasad** [comment]
Hey @Pratik-11,
Working in brave browser at my end. 🤷‍♀️

Adding the screenshot 
<img width="1792" alt="Screenshot 2023-05-28 at 4 14 25 PM" src="https://github.com/foss42/api-dash/assets/1382619/867a10fe-d7ed-4c23-930c-ff8a8fba195a">

**Comment by Pratik-11** [comment]
lol idk my brave is dead ig 🤔

**Comment by ashitaprasad** [comment]
No worries @Pratik-11. 🙂
