### ISSUE TITLE
Readme.md video not playable on Firefox 113.0.2

### ISSUE THREAD

**Issue by aguilaair** [foss42/api-dash#44]
**Feedback**
The Readme.md video not playable on Firefox 113.0.2. It would be nice if it could be updated to play on all browsers.

Thanks!

<img width="850" alt="image" src="https://github.com/foss42/api-dash/assets/29983481/640fdddb-6318-4c93-9aa8-39205cf662b9">

**Comment by animator** [comment]
Hi @aguilaair, Thanks for reporting the issue. Seems to be GitHub/Browser issue. 
We have now also added a youtube link to the demo video as a fail safe in case the embedded video shows an error. 
Commit 736fd89276edf7ee6b4ffd7a161d2948b8a691c9
