### ISSUE TITLE
Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by ImranNawar** [foss42/api-dash#46]
Hi there!
I recommend adding a **CODE_OF_CONDUCT.md** file to your repository. This file would serve as a guide for potential contributors, providing them with a clear set of expectations, guidelines, and behavior standards for participating in your project. It plays an essential role in creating a welcoming and inclusive environment for everyone involved.

I would like to work on this issue. Please assign it to me under **GSSoC'23**.

Thank you!

**Comment by animator** [comment]
Hi @ImranNawar, 

Thanks for your interest in making meaningful contribution to this project.
Please go through [FAQs & Getting Started Guide for GSSoC students](https://github.com/foss42/api-dash/discussions/45) to get started with your first contribution to this project.
Closing this issue as GitHub already provides a template to add CODE_OF_CONDUCT.md

Thanks.
