### ISSUE TITLE
Missing PR template

### ISSUE THREAD

**Issue by Anshika-Jain02** [foss42/api-dash#49]
**Addition of Pull Request Template to improve clarity and to make it easier for new contributors.**

**Please assign this issue to me under GSSoC'23 @animator**

**Comment by animator** [comment]
Hi @Anshika-Jain02 ,

Thanks for your interest in making meaningful contribution to this project.
Please go through [FAQs & Getting Started Guide for GSSoC students](https://github.com/foss42/api-dash/discussions/45) to get started with your first contribution to this project.
Closing this issue as we have already outlined how to create a PR in the Contributing Guide.

Thanks.
