### ISSUE TITLE
[FIX] Additions in Issue template

### ISSUE THREAD

**Issue by Anshika-Jain02** [foss42/api-dash#50]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, documentation, etc*

**Please assign this issue to me under Gssoc'23 @animator**

**Comment by animator** [comment]
Hi @Anshika-Jain02 ,

Thanks for your interest in making meaningful contribution to this project.
Please go through [FAQs & Getting Started Guide for GSSoC students](https://github.com/foss42/api-dash/discussions/45) to get started with your first contribution to this project.
Closing this issue as we already have the requisite issue templates.

Thanks.
