### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by andoriyaprashant** [foss42/api-dash#54]
## Describe the bug/problem

- Adding a PR template
- Template path .github\pull_request_template.md

## Steps to Reproduce the bug/problem
- Go to .github file 
- See error

## Expected behavior
Repo with pull request template

## Screenshots
![Screenshot 2023-05-29 233408](https://github.com/foss42/api-dash/assets/121665385/88f21277-ca79-4452-847f-02f49eba0a77)
![Screenshot 2023-05-29 233534](https://github.com/foss42/api-dash/assets/121665385/11e238b9-c859-40e3-8062-e63d699be302)

**Comment by andoriyaprashant** [comment]
Hello @animator 
Please review my Pull request #55 
Thank you

**Comment by animator** [comment]
Hi @andoriyaprashant,

Thanks for your interest in making meaningful contribution to this project.
Please go through [FAQs & Getting Started Guide for GSSoC students](https://github.com/foss42/api-dash/discussions/45) to get started with your first contribution to this project.
Closing this issue as we have already outlined how to create a PR in the Contributing Guide.

Thanks.

**Comment by andoriyaprashant** [comment]
@animator But I think Pull request template is imp 
Here are official docs too - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
