### ISSUE TITLE
[feat]: add a github action workflow for greeting contributors

### ISSUE THREAD

**Issue by harmeetsingh11** [foss42/api-dash#57]
### Is your feature request related to a problem? Please describe.
Currently, this project does not have any action to greet to contributors. Github action is the great tool to automate the manual stuff for your project.

### Describe the solution you'd like.
I would like to add a action workflow. This feature would automatically greet the author when specific event happens like:
- When an issue is opened.
- When a pull request is opened and merged.
- When an issue is closed.
- When an issue is assigned to someone, it notifies the assignee and start working.

### How would this feature be beneficial for the project
- The communication and engagement with the contributors will be improved.
- It automates the process of manually greeting the contributors.

### Record
- [x] I agree to follow project's contribution guidelines
- [x] I am a GSSoC'23 contributor
- [x] I want work on this issue

Please assign me this issue under GSS0C'23
Thanks.

**Comment by ashitaprasad** [comment]
Thanks, but we don't need it as we actively engage with our contributors.
