### ISSUE TITLE
Create Issue forms in the repo

### ISSUE THREAD

**Issue by dakshsinghrathore** [foss42/api-dash#59]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
Currently the contributor has to raise an issue from ground zero without any ***prebuilt forms***, to gain a better understanding of the issue raised we can create ***custom issue forms*** which will be ***visually appealing*** as well as be ***hassle free*** for the contributor to express their concern in an ***ordered manner*** .

**Describe the solution/feature you'd like us to add**
I will be deleting all the existing .md files under the issuetemplates and add _yaml code_ for the respective forms.

Currently 👇

 
![Screenshot 2023-06-14 at 15-04-07 New Issue · foss42_api-dash](https://github.com/foss42/api-dash/assets/115932772/44f38825-ac4c-4671-8ee8-f01df102dfbb)

Coming 👇

![Screenshot 2023-06-13 at 23-28-00 New Issue · priyankarpal_ProjectsHut](https://github.com/UBA-GCOEN/StichHub/assets/115932772/ddab78a8-99ad-4c78-ad35-525a7d30e89b)

**Any other feedback you would like to provide regarding the site**
_Your response here_

**Comment by dakshsinghrathore** [comment]
Kindly assign this issue to me @animator

**Comment by animator** [comment]
Thanks for your interest in contributing to the project @dakshsinghrathore 
Currently, we are planning to stick to the GitHub issue template.
Do check out https://github.com/foss42/api-dash/issues/56
