### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by mazab99** [foss42/api-dash#6]

**Comment by animator** [comment]
Download the installers from [here](https://github.com/foss42/api-dash#download)

You can check out installation instructions with video [here](https://github.com/foss42/api-dash/blob/main/INSTALLATION.md).

Once the installation is complete. You can simply open the API Dash application from the start menu (Windows) or App Launchpad (MacOS).

Now click on the "+ New" button on the top-left to create a new request and proceed as shown in the video [here](https://github.com/foss42/api-dash#download)
