### ISSUE TITLE
Addition of auto-comment.yml file

### ISSUE THREAD

**Issue by DivyanshiNarang** [foss42/api-dash#62]
We need to add an auto-comment.yml that will automatically welcome, greet and provide necessary information to the contributors when they create new issues, PR, and when these will get assigned or merged respectively. This will promote motivation and performance.

@foss42 Please assign me this issue under gssoc'23

**Comment by animator** [comment]
Thanks for your interest in contributing to the project @DivyanshiNarang 
We prefer engaging with the contributors directly.
Do check out https://github.com/foss42/api-dash/issues/56
