### ISSUE TITLE
Addition of dependabot.yml file

### ISSUE THREAD

**Issue by DivyanshiNarang** [foss42/api-dash#63]
We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.

@foss42 please assign me this issue under gssoc'23.

**Comment by animator** [comment]
We closely track the changelog of the packages we use and update the dependencies, hence we are currently not planning to use dependabot.
Read more https://github.com/foss42/api-dash/issues/56
