### ISSUE TITLE
Issues Template Modify

### ISSUE THREAD

**Issue by parasss19** [foss42/api-dash#68]
## Issue 1
- Issue template files are in .md format which is not looking good 
-  it doesn't have separate columns for content and drop down menu and checkboxes
### Current View
<img width="713" alt="Screenshot 2023-06-27 111124" src="https://github.com/foss42/api-dash/assets/101205226/88d925b8-ec40-489f-80a8-57e3331d519a">

### Solution 
- I will write yml code for issues template 
- I will add drop down menu for operating systems, Device, Version, browser etc.
- Sample 
<img width="721" alt="temp img" src="https://github.com/foss42/api-dash/assets/101205226/d6e597ec-f0bb-4b05-b2d0-ad6da49eaf01">

## Issue 2
- There are no checkboxes in issue template
- When contributor (GSSOC'23) raise a new issue then many time they didn't mention GSSOC label
- It is also tough for project admin to label the issues
### Solution 
- I will add important checkboxes in issue template (sample below)
<img width="930" alt="2023-06-20" src="https://github.com/foss42/api-dash/assets/101205226/89cab393-965c-4bcc-b205-646bbaa80c82">

**Comment by animator** [comment]
Hi @parasss19 
Thanks for your interest in contributing to the project.
We are currently not accepting any issue template modification.
Do check out https://github.com/foss42/api-dash/issues/56 to contribute to this project.
