### ISSUE TITLE
scroll bar is misaligned

### ISSUE THREAD

**Issue by Saimurugeshwari** [foss42/api-dash#69]
Scroll bar misallocate:

![Screenshot 2023-06-28 133154](https://github.com/foss42/api-dash/assets/103344341/abfe25e5-8eaf-41ba-9b2d-82b06d7742bc)

Device:
windows 11, edge browser

**Comment by Saimurugeshwari** [comment]
its should be corner or fit to the window.

**Comment by animator** [comment]
Thanks for catching this bug @Saimurugeshwari 
Please feel free to send a PR to fix this issue.

**Comment by Saimurugeshwari** [comment]
Sure, I fixed but to retest that once again

**Comment by animator** [comment]
@Saimurugeshwari any updates?

**Comment by Saimurugeshwari** [comment]
Yes, I have fixed. I need to raise a PR request since my system has some issue. It's getting late. I will raise PR request within tomorrow.

**Comment by animator** [comment]
Ok @Saimurugeshwari .. no problem.

**Comment by Saimurugeshwari** [comment]
Update on this issue, I have changed relevant code but I couldn't test with live location because of VS code issue. It through Exception  error because of that PR request getting delayed, I will raise a request withing today or tomorrow morning.

**Comment by animator** [comment]
okay @Saimurugeshwari

**Comment by suman-somu** [comment]
Taking this issue

**Comment by animator** [comment]
Sure @suman-somu .. feel free to send a PR.

**Comment by animator** [comment]
Closing this issue as it has already been fixed in the main branch.
