### ISSUE TITLE
Adding a Contributors button at the left side Navigation bar.

### ISSUE THREAD

**Issue by aritroo** [foss42/api-dash#71]
I want to add a **contributors button** at the left side of the **navigation bar**.

after clicking on that button it will redirect you to new page where it will show about the contributors details on that page of the application.

Please assign me this issue for **gssoc'23**. I would love to work on it.

**Comment by animator** [comment]
Thanks for your interest in contributing to the project.
The suggested feature does not add much value for the end user, so we have decided not to go ahead with it.
There are currently plenty of open issues which require help, so you can definitely look into them.
Thanks!
