### ISSUE TITLE
Field to enter headers/params gets disabled

### ISSUE THREAD

**Issue by Mixel2004** [foss42/api-dash#73]
**Describe the bug/problem**
In the field to enter params and headers there is no check if the user tried to remove the last index. So if the remove button is pressed, the row size becomes 0 and if pushed again, it throws an error disabling the field.

**Steps to Reproduce the bug/problem**
Click the remove button twice and resize the application to force rebuild it and then the field gets disabled

Note:
This is the remove button I am referring to in this issue.
![image](https://github.com/foss42/api-dash/assets/84668201/5cebb576-14f3-4c10-b29e-45f98c21b2a5)

![image](https://github.com/foss42/api-dash/assets/84668201/6b434320-874f-4663-b325-14cc780917c9)

**Comment by animator** [comment]
Hi @Mixel2004 thanks for reporting. Feel free to send a PR in case you have already resolved it or want to resolve it.
