### ISSUE TITLE
Feature Request: Designing a website for "API Dash"

### ISSUE THREAD

**Issue by yaten2302** [foss42/api-dash#75]
**Describe the solution/feature you'd like us to add**
Hi @animator, I was having an idea of designing a website for "API Dash".

Here all the details of the project will be added with some demo screenshots, videos, features and some description.
Also there can be a "Contact page" and "FAQs section". This will be easier for the user to get to know about the project very easily.

Also it will attract more users because of the beautiful UI of the website and the app.

Please assign this task to me under GSSOC'23, as I want to work on this issue 🙏🙏

**Comment by ashitaprasad** [comment]
Hi @yaten2302,
Thanks for your interest in contributing to the project. We already have a website at https://foss42.com/ and in case you want to suggest any improvements, you can do so in this thread.

**Comment by yaten2302** [comment]
Hi @ashitaprasad, could you tell that is this website using HTML, CSS and JavaScript as tech stack?

**Comment by yaten2302** [comment]
I can make the dark mode of the website, if it is made using HTML, CSS and JavaScript.

**Comment by animator** [comment]
We currently do not need a dark mode website as it is not content heavy.

**Comment by yaten2302** [comment]
Oh, ok, so should I close this issue? I will try to contribute to this project by finding some other issues👍

**Comment by animator** [comment]
Sure. You can go ahead and close this issue.
Looking forward to your contribution 👍
