### ISSUE TITLE
Adding a MIT Licenses badge and a Licenses section in readme

### ISSUE THREAD

**Issue by 1Shubham7** [foss42/api-dash#77]
**Tell us about the task you want to perform and are unable to do so because the feature is not available**
The readme file of the repo should have a Licenses badge and some text regarding licenses in the Licenses section to make it more professional.

![afters](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/df57e4ed-2b1c-4236-b95d-17c9f3190e5a)

**Describe the solution/feature you'd like us to add**
I can add a licenses section and a MIT licenses badge

**Any other feedback you would like to provide regarding the site**
the project is great

**Comment by ashitaprasad** [comment]
Hi @1Shubham7,

Thanks for your interest in contributing to the project.
We already have a license file in the repo.
Do check out https://github.com/foss42/api-dash/issues/56 to contribute to this project.
